# ============================================================================
# add_lysmer.py  --  emit LysmerTriangle absorbing dashpots on the DRM box
# ----------------------------------------------------------------------------
# For a DRM box, the exterior carries only the SCATTERED field (the DRM ring
# injects the free-field), so BARE Lysmer dashpots are the correct, standard
# absorbing boundary (lysmer_asd_absorbing_boundaries_guide.md §7.2). This
# stabilizes the otherwise free box (kills the rigid-body drift) so the interior
# reproduces the prescribed DRM field.
#
# LysmerTriangle is a 3-node facet dashpot: diag(rho*Vs, rho*Vs, rho*Vp) in
# (t,s,n), auto-scaled by facet area. stage 0 (default) = pure dashpot, no
# gravity/staging needed for this elastic kinematic test. Facet winding is
# irrelevant for damping (|velocity|-based), so any valid triangulation works.
#
# Applied to the 5 non-top faces (4 sides + bottom); top (z=0) is the free
# surface. Tags start at 1000 to avoid the 48 brick tags.
# ============================================================================
import os, re
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
MODEL_TCL = os.path.join(HERE, "drm_model.tcl")
OUT = os.path.join(HERE, "lysmer_elements.tcl")

# soil (must match build_drm_model.py)
Vp, Vs, rho = 4000.0, 2000.0, 2600.0

# parse nodes from the emitted deck -> coord->tag
nodes = {}
for line in open(MODEL_TCL):
    m = re.match(r'\s*node\s+(\d+)\s+([-\d.eE+]+)\s+([-\d.eE+]+)\s+([-\d.eE+]+)', line)
    if m:
        nodes[(round(float(m[2]), 3), round(float(m[3]), 3), round(float(m[4]), 3))] = int(m[1])

xs = sorted({k[0] for k in nodes})
ys = sorted({k[1] for k in nodes})
zs = sorted({k[2] for k in nodes})
zmin, zmax = zs[0], zs[-1]   # zmin=0 surface (top, z-down), zmax=150 bottom
print(f"grid x={xs}\n     y={ys}\n     z={zs}  (top/free=z{zmin}, bottom=z{zmax})")


def tag(x, y, z):
    return nodes[(round(x, 3), round(y, 3), round(z, 3))]


facets = []   # each = (na, nb, nc)


def add_quad(p00, p10, p11, p01):
    a, b, c, d = tag(*p00), tag(*p10), tag(*p11), tag(*p01)
    facets.append((a, b, c))
    facets.append((a, c, d))


# bottom face z=zmax (all x-y cells)
for i in range(len(xs) - 1):
    for j in range(len(ys) - 1):
        add_quad((xs[i], ys[j], zmax), (xs[i+1], ys[j], zmax),
                 (xs[i+1], ys[j+1], zmax), (xs[i], ys[j+1], zmax))
# x = xmin and x = xmax side faces (y-z cells)
for xf in (xs[0], xs[-1]):
    for j in range(len(ys) - 1):
        for k in range(len(zs) - 1):
            add_quad((xf, ys[j], zs[k]), (xf, ys[j+1], zs[k]),
                     (xf, ys[j+1], zs[k+1]), (xf, ys[j], zs[k+1]))
# y = ymin and y = ymax side faces (x-z cells)
for yf in (ys[0], ys[-1]):
    for i in range(len(xs) - 1):
        for k in range(len(zs) - 1):
            add_quad((xs[i], yf, zs[k]), (xs[i+1], yf, zs[k]),
                     (xs[i+1], yf, zs[k+1]), (xs[i], yf, zs[k+1]))

with open(OUT, "w") as f:
    f.write("# LysmerTriangle absorbing dashpots (bare, for DRM scattered field)\n")
    f.write("# generated by add_lysmer.py\n")
    t = 1000
    for (a, b, c) in facets:
        f.write(f"element LysmerTriangle {t} {a} {b} {c} {rho} {Vp} {Vs}\n")
        t += 1
print(f"wrote {len(facets)} LysmerTriangle facets -> {OUT}")
print("PASS")
