# ============================================================================
# setup_tcl_run.py  --  prepare the Tcl-path baseline run
# ----------------------------------------------------------------------------
# The fork openseespy `pattern` dispatcher does NOT register H5DRM (only the
# Tcl interpreter does, 3-arg: tag file factor). The Tcl 3-arg path uses the
# constructor default do_coordinate_transformation=true with crd_scale=1,
# identity T, x0=0 => transform = (xyz - drmbox_x0). So if we rescale the
# .h5drm coords to METERS (drmbox_x0 -> [6000,8000,0]), the transform yields
# (xyz_m - [6000,8000,0]) = our CENTERED model coords. No crd_scale needed.
#
# Produces:  drm_small_m.h5drm  (meters)  +  drm_run.tcl  (driver)
# ============================================================================
import os
import shutil
import numpy as np
import h5py

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "drm_small.h5drm")
DST = os.path.join(HERE, "drm_small_m.h5drm")
TCL = os.path.join(HERE, "drm_run.tcl")
DISP_OUT = os.path.join(HERE, "drm_disp_tcl.out")
SCALE = 1000.0
DT = 0.025
N_STEPS = 1180  # 29.5 s, just short of tend=30 (avoid the tend read-overrun exit(-1))
CENTER_KM = np.array([6.0, 8.0, 0.0])

# --- 1. meters copy ---------------------------------------------------------
shutil.copyfile(SRC, DST)
with h5py.File(DST, "r+") as f:
    f["DRM_Data/xyz"][...] = f["DRM_Data/xyz"][:] * SCALE
    md = f["DRM_Metadata"]
    md["drmbox_x0"][...] = md["drmbox_x0"][:] * SCALE
    for k in ("drmbox_xmin", "drmbox_xmax", "drmbox_ymin", "drmbox_ymax",
              "drmbox_zmin", "drmbox_zmax"):
        md[k][...] = md[k][()] * SCALE
    # motion (disp/vel/acc) and dt stay in SI (m) — unchanged.
print("wrote meters dataset:", DST)

# --- 2. pick an interior comparison node + its prescribed row ---------------
with h5py.File(SRC, "r") as f:
    sxyz = f["DRM_Data/xyz"][:]
    internal = f["DRM_Data/internal"][:]
    dloc = f["DRM_Data/data_location"][:]
# nearest INTERIOR station to the box center
ii = np.where(internal)[0]
i_cmp = ii[int(np.argmin(np.linalg.norm(sxyz[ii] - CENTER_KM, axis=1)))]
row0 = int(dloc[i_cmp])
model_xyz = (sxyz[i_cmp] - CENTER_KM) * SCALE
np.savez(os.path.join(HERE, "_cmp_meta.npz"),
         i_cmp=i_cmp, row0=row0, model_xyz=model_xyz, station_km=sxyz[i_cmp])
print(f"comparison interior station #{i_cmp} xyz_km={sxyz[i_cmp]} -> model {model_xyz} row0={row0}")

# --- 3. Tcl driver ----------------------------------------------------------
tcl = f"""# baseline DRM run (current fork binary) -- generated by setup_tcl_run.py
source "{os.path.join(HERE, 'drm_model.tcl').replace(os.sep, '/')}"

# H5DRM load pattern. With the runtime-pattern.cpp full-arg fix, crd_scale and an
# identity-default transform are honored, so the ORIGINAL km dataset works:
#   transform = (xyz_km - drmbox_x0_km) * crd_scale = (station-center)*1000 = centered-m model
pattern H5DRM 1 "{SRC.replace(os.sep, '/')}" 1.0 {SCALE} 1.0 1

# record the interior comparison node (model coords {tuple(np.round(model_xyz,3))})
set cmpnode [lindex [getNodeTags] 0]
foreach nt [getNodeTags] {{
    set c [nodeCoord $nt]
    set dx [expr [lindex $c 0] - ({model_xyz[0]})]
    set dy [expr [lindex $c 1] - ({model_xyz[1]})]
    set dz [expr [lindex $c 2] - ({model_xyz[2]})]
    if {{ [expr $dx*$dx + $dy*$dy + $dz*$dz] < 1.0e-3 }} {{ set cmpnode $nt }}
}}
puts "comparison node tag = $cmpnode coords [nodeCoord $cmpnode]"
recorder Node -file "{DISP_OUT.replace(os.sep, '/')}" -time -node $cmpnode -dof 1 2 3 disp

constraints Plain
numberer RCM
system BandGeneral
test NormDispIncr 1.0e-8 10
algorithm Linear
integrator Newmark 0.5 0.25
analysis Transient

set nfail 0
for {{set i 0}} {{$i < {N_STEPS}}} {{incr i}} {{
    if {{ [analyze 1 {DT}] != 0 }} {{ incr nfail; puts "analyze failed at step $i"; break }}
}}
puts "DONE nfail=$nfail"
wipe
"""
open(TCL, "w").write(tcl)
print("wrote Tcl driver:", TCL)
print("PASS")
