"""
PyEmitter — accumulates an openseespy Python deck as a list of strings.

Each Protocol method appends one ``ops.X(...)`` call to ``_lines``.
The Tcl block dialect (``\\{`` / ``\\}``) becomes openseespy's
"current section / current pattern" implicit state; patches, fibers,
layers, and loads following an open call attach to that state by
convention. ``section_close`` and ``pattern_close`` are no-ops in
the Python output (the next non-block-bodied call ends the implicit
scope).

The generated script imports openseespy and calls ``ops.wipe()`` once
at the top so re-running the script in a stateful Python session does
not pollute prior state.
"""
from __future__ import annotations

from typing import Any


__all__ = ["PyEmitter"]


def _fmt_value(v: Any) -> str:
    """Render one positional argument for a Python source line.

    Strings are wrapped in single quotes (Python source). Booleans
    coerce to ``1`` / ``0`` (openseespy does not accept Python bools).
    Integers and floats use their ``repr`` (round-trip-safe).
    """
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, str):
        # Single-quote Python string literal; escape embedded single
        # quotes. OpenSees vocabulary doesn't typically include
        # quotes, but defensively handle the case.
        escaped = v.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    return repr(v)


def _ops_call(method: str, *args: Any) -> str:
    """Render an ``ops.<method>(...)`` source line."""
    rendered = ", ".join(_fmt_value(a) for a in args)
    return f"ops.{method}({rendered})"


class PyEmitter:
    """Accumulates an openseespy Python deck.

    The output is a self-contained Python script: the user can write
    it to disk, ``python script.py`` it, and OpenSees will execute the
    deck. Top-level statements; no function wrapper.
    """

    def __init__(self) -> None:
        self._lines: list[str] = [
            "# auto-generated by apeGmsh.opensees; do not edit by hand",
            "import openseespy.opensees as ops",
            "ops.wipe()",
        ]

    # -- Output --------------------------------------------------------------

    def lines(self) -> list[str]:
        """Return a copy of the accumulated Python lines."""
        return list(self._lines)

    # -- Model ---------------------------------------------------------------

    def model(self, *, ndm: int, ndf: int) -> None:
        # openseespy.model takes positional + flag-style args:
        # ops.model('basic', '-ndm', 3, '-ndf', 6).
        self._lines.append(
            _ops_call("model", "basic", "-ndm", ndm, "-ndf", ndf)
        )

    def node(self, tag: int, *coords: float) -> None:
        self._lines.append(_ops_call("node", tag, *coords))

    def fix(self, tag: int, *dofs: int) -> None:
        self._lines.append(_ops_call("fix", tag, *dofs))

    def mass(self, tag: int, *values: float) -> None:
        self._lines.append(_ops_call("mass", tag, *values))

    # -- Constitutive --------------------------------------------------------

    def uniaxialMaterial(
        self, mat_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(
            _ops_call("uniaxialMaterial", mat_type, tag, *params)
        )

    def nDMaterial(
        self, mat_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(_ops_call("nDMaterial", mat_type, tag, *params))

    def section(
        self, sec_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(_ops_call("section", sec_type, tag, *params))

    def geomTransf(self, t_type: str, tag: int, *vec: float) -> None:
        self._lines.append(_ops_call("geomTransf", t_type, tag, *vec))

    # -- Sections that take blocks (Fiber) ----------------------------------

    def section_open(
        self, sec_type: str, tag: int, *params: float | str,
    ) -> None:
        # openseespy's stateful "current section" is set by the same
        # ops.section() call that defines the section's parameters.
        self._lines.append(_ops_call("section", sec_type, tag, *params))

    def section_close(self) -> None:
        # No-op — openseespy doesn't have an explicit close. The
        # current-section context ends implicitly when a non-patch /
        # non-fiber / non-layer command runs next.
        pass

    def patch(self, kind: str, *args: int | float) -> None:
        self._lines.append(_ops_call("patch", kind, *args))

    def fiber(
        self, y: float, z: float, area: float, mat_tag: int,
    ) -> None:
        self._lines.append(_ops_call("fiber", y, z, area, mat_tag))

    def layer(self, kind: str, *args: int | float) -> None:
        self._lines.append(_ops_call("layer", kind, *args))

    # -- Beam integration rules ---------------------------------------------

    def beamIntegration(
        self, rule_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_ops_call("beamIntegration", rule_type, tag, *args))

    # -- Topology ------------------------------------------------------------

    def element(
        self, ele_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_ops_call("element", ele_type, tag, *args))

    # -- Time series --------------------------------------------------------

    def timeSeries(
        self, ts_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_ops_call("timeSeries", ts_type, tag, *args))

    # -- Patterns -----------------------------------------------------------

    def pattern_open(
        self, p_type: str, tag: int, *args: int | float | str,
    ) -> None:
        # Same shape as section_open — openseespy's current-pattern
        # state is opened by ops.pattern(...).
        self._lines.append(_ops_call("pattern", p_type, tag, *args))

    def pattern_close(self) -> None:
        # No-op — see section_close.
        pass

    def load(self, tag: int, *forces: float) -> None:
        self._lines.append(_ops_call("load", tag, *forces))

    def eleLoad(self, *args: int | float | str) -> None:
        self._lines.append(_ops_call("eleLoad", *args))

    def sp(self, tag: int, dof: int, value: float) -> None:
        self._lines.append(_ops_call("sp", tag, dof, value))

    # -- Recorders ----------------------------------------------------------

    def recorder(self, kind: str, *args: int | float | str) -> None:
        self._lines.append(_ops_call("recorder", kind, *args))

    def recorder_declaration_begin(
        self,
        *,
        declaration_name: str,
        record_name: str | None,
        category: str,
        components: tuple[str, ...],
        raw: tuple[str, ...] = (),
        pg: tuple[str, ...] = (),
        label: tuple[str, ...] = (),
        selection: tuple[str, ...] = (),
        ids: tuple[int, ...] | None = None,
        dt: float | None = None,
        n_steps: int | None = None,
        file_root: str = ".",
    ) -> None:
        """Phase 9 schema 2.3.0 declaration metadata — no-op for openseespy."""
        del (
            declaration_name, record_name, category, components, raw,
            pg, label, selection, ids, dt, n_steps, file_root,
        )

    def recorder_declaration_end(self) -> None:
        """Phase 9 schema 2.3.0 declaration metadata — no-op for openseespy."""

    # -- Analysis chain -----------------------------------------------------

    def constraints(self, c_type: str, *args: float) -> None:
        self._lines.append(_ops_call("constraints", c_type, *args))

    def numberer(self, n_type: str) -> None:
        self._lines.append(_ops_call("numberer", n_type))

    def system(self, s_type: str, *args: int | float | str) -> None:
        self._lines.append(_ops_call("system", s_type, *args))

    def test(self, t_type: str, *args: int | float | str) -> None:
        self._lines.append(_ops_call("test", t_type, *args))

    def algorithm(self, a_type: str, *args: int | float | str) -> None:
        self._lines.append(_ops_call("algorithm", a_type, *args))

    def integrator(self, i_type: str, *args: int | float | str) -> None:
        self._lines.append(_ops_call("integrator", i_type, *args))

    def analysis(self, a_type: str) -> None:
        self._lines.append(_ops_call("analysis", a_type))

    def analyze(self, *, steps: int, dt: float | None = None) -> int:
        if dt is None:
            self._lines.append(_ops_call("analyze", steps))
        else:
            self._lines.append(_ops_call("analyze", steps, dt))
        return 0
