"""
PyEmitter — accumulates an openseespy Python deck as a list of strings.

Each Protocol method appends one ``ops.X(...)`` call to ``_lines``.
The Tcl block dialect (``\\{`` / ``\\}``) becomes openseespy's
"current section / current pattern" implicit state; patches, fibers,
layers, and loads following an open call attach to that state by
convention. ``section_close`` and ``pattern_close`` are no-ops in
the Python output (the next non-block-bodied call ends the implicit
scope).

The generated script imports openseespy and calls ``ops.wipe()`` once
at the top so re-running the script in a stateful Python session does
not pollute prior state.
"""
from __future__ import annotations

from typing import Any, Literal


__all__ = ["PyEmitter"]


class _LineBuf(list[str]):
    """Line buffer with an optional partition-indent prefix.

    Behaves as a plain ``list[str]`` for ``insert``, iteration, slicing,
    and the ``lines()`` copy-out. When ``indent`` is non-empty, every
    ``append(line)`` prepends ``indent`` to ``line`` before storing.
    This keeps the existing ``self._lines.append(...)`` call sites in
    :class:`PyEmitter` working unchanged while
    ``partition_open(K)`` / ``partition_close()`` toggle the indent.
    """

    __slots__ = ("indent",)

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.indent: str = ""

    def append(self, line: str) -> None:  # type: ignore[override]
        if self.indent:
            super().append(self.indent + line)
        else:
            super().append(line)


def _fmt_value(v: Any) -> str:
    """Render one positional argument for a Python source line.

    Strings are wrapped in single quotes (Python source). Booleans
    coerce to ``1`` / ``0`` (openseespy does not accept Python bools).
    Integers and floats use their ``repr`` (round-trip-safe).
    """
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, str):
        # Single-quote Python string literal; escape embedded single
        # quotes. OpenSees vocabulary doesn't typically include
        # quotes, but defensively handle the case.
        escaped = v.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    return repr(v)


def _ops_call(method: str, *args: Any) -> str:
    """Render an ``ops.<method>(...)`` source line."""
    rendered = ", ".join(_fmt_value(a) for a in args)
    return f"ops.{method}({rendered})"


class PyEmitter:
    """Accumulates an openseespy Python deck.

    The output is a self-contained Python script: the user can write
    it to disk, ``python script.py`` it, and OpenSees will execute the
    deck. Top-level statements; no function wrapper.
    """

    def __init__(self) -> None:
        # ``_lines`` is a :class:`_LineBuf` so ``partition_open`` can
        # toggle a per-rank indent without every ``append`` call site
        # needing to know. All existing primitives keep calling
        # ``self._lines.append(...)`` unchanged.
        self._lines: _LineBuf = _LineBuf([
            "# auto-generated by apeGmsh.opensees; do not edit by hand",
            "import openseespy.opensees as ops",
            "ops.wipe()",
        ])
        # Partition-emission state (ADR 0027 / P4). On the first
        # ``partition_open`` call across the emitter's lifetime, emit a
        # one-shot runtime shim that pulls ``getPID`` from openseespy
        # but falls back to a 0-returning stub so single-process
        # Python still runs the deck.
        self._partition_shim_emitted: bool = False
        # Step-hook state (Phase SSI-1).  Mirror of the TclEmitter
        # flags: ``_step_hooks_registered`` flips on the first
        # ``step_hook_ramp`` and is checked by ``analyze`` to wrap the
        # analyze loop with dispatcher calls.
        # ``_hook_dispatcher_emitted`` ensures the dispatcher
        # boilerplate (module-level lists + dispatcher functions) is
        # emitted exactly once.
        self._step_hooks_registered: bool = False
        self._hook_dispatcher_emitted: bool = False

    # -- Output --------------------------------------------------------------

    def lines(self) -> list[str]:
        """Return a copy of the accumulated Python lines."""
        return list(self._lines)

    # -- Model ---------------------------------------------------------------

    def model(self, *, ndm: int, ndf: int) -> None:
        # openseespy.model takes positional + flag-style args:
        # ops.model('basic', '-ndm', 3, '-ndf', 6).
        self._lines.append(
            _ops_call("model", "basic", "-ndm", ndm, "-ndf", ndf)
        )

    def node(
        self, tag: int, *coords: float, ndf: int | None = None,
    ) -> None:
        if ndf is None:
            self._lines.append(_ops_call("node", tag, *coords))
        else:
            # Per-node ``-ndf`` override for mixed-ndf models (e.g. 6-DOF
            # phantom nodes in an ndf=3 solid mesh; ADR 0022 INV-3).
            self._lines.append(
                _ops_call("node", tag, *coords, "-ndf", ndf)
            )

    def fix(self, tag: int, *dofs: int) -> None:
        self._lines.append(_ops_call("fix", tag, *dofs))

    def mass(self, tag: int, *values: float) -> None:
        self._lines.append(_ops_call("mass", tag, *values))

    # -- MP constraints (ADR 0022, Phase 7b) -----------------------------

    def equalDOF(self, master: int, slave: int, *dofs: int) -> None:
        self._lines.append(_ops_call("equalDOF", master, slave, *dofs))

    def rigidLink(self, kind: str, master: int, slave: int) -> None:
        self._lines.append(_ops_call("rigidLink", kind, master, slave))

    def rigidDiaphragm(
        self, perp_dir: int, master: int, *slaves: int,
    ) -> None:
        self._lines.append(
            _ops_call("rigidDiaphragm", perp_dir, master, *slaves)
        )

    def embeddedNode(
        self, ele_tag: int, cnode: int, *master_nodes: int,
        stiffness: float = 1.0e18,
        stiffness_p: float | None = None,
        rotational: bool = False,
        pressure: bool = False,
    ) -> None:
        from .base import _build_embedded_flag_args
        flag_args = _build_embedded_flag_args(
            stiffness, stiffness_p, rotational, pressure,
        )
        self._lines.append(
            _ops_call(
                "element", "ASDEmbeddedNodeElement",
                ele_tag, cnode, *master_nodes, *flag_args,
            )
        )

    def mp_constraint_comment(self, name: str) -> None:
        # Hash-comment line, matching Tcl's ``# {name}`` convention.
        self._lines.append(f"# {name}")

    # -- Regions -------------------------------------------------------------

    def region(self, tag: int, *args: int | float | str) -> None:
        self._lines.append(_ops_call("region", tag, *args))

    # -- Damping (ADR 0053) --------------------------------------------------

    def rayleigh(
        self,
        alpha_m: float,
        beta_k: float,
        beta_k_init: float,
        beta_k_comm: float,
    ) -> None:
        self._lines.append(
            _ops_call("rayleigh", alpha_m, beta_k, beta_k_init, beta_k_comm),
        )

    def damping(
        self, damp_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_ops_call("damping", damp_type, tag, *args))

    # -- Constitutive --------------------------------------------------------

    def uniaxialMaterial(
        self, mat_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(
            _ops_call("uniaxialMaterial", mat_type, tag, *params)
        )

    def nDMaterial(
        self, mat_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(_ops_call("nDMaterial", mat_type, tag, *params))

    def section(
        self, sec_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(_ops_call("section", sec_type, tag, *params))

    def geomTransf(self, t_type: str, tag: int, *vec: float) -> None:
        self._lines.append(_ops_call("geomTransf", t_type, tag, *vec))

    # -- Sections that take blocks (Fiber) ----------------------------------

    def section_open(
        self, sec_type: str, tag: int, *params: float | str,
    ) -> None:
        # openseespy's stateful "current section" is set by the same
        # ops.section() call that defines the section's parameters.
        self._lines.append(_ops_call("section", sec_type, tag, *params))

    def section_close(self) -> None:
        # No-op — openseespy doesn't have an explicit close. The
        # current-section context ends implicitly when a non-patch /
        # non-fiber / non-layer command runs next.
        pass

    def patch(self, kind: str, *args: int | float) -> None:
        self._lines.append(_ops_call("patch", kind, *args))

    def fiber(
        self, y: float, z: float, area: float, mat_tag: int,
    ) -> None:
        self._lines.append(_ops_call("fiber", y, z, area, mat_tag))

    def layer(self, kind: str, *args: int | float) -> None:
        self._lines.append(_ops_call("layer", kind, *args))

    # -- Beam integration rules ---------------------------------------------

    def beamIntegration(
        self, rule_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_ops_call("beamIntegration", rule_type, tag, *args))

    # -- Topology ------------------------------------------------------------

    def element(
        self, ele_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_ops_call("element", ele_type, tag, *args))

    # -- Time series --------------------------------------------------------

    def timeSeries(
        self, ts_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_ops_call("timeSeries", ts_type, tag, *args))

    # -- Patterns -----------------------------------------------------------

    def pattern_open(
        self, p_type: str, tag: int, *args: int | float | str,
    ) -> None:
        # Same shape as section_open — openseespy's current-pattern
        # state is opened by ops.pattern(...).
        self._lines.append(_ops_call("pattern", p_type, tag, *args))

    def pattern_close(self) -> None:
        # No-op — see section_close.
        pass

    def load(self, tag: int, *forces: float) -> None:
        self._lines.append(_ops_call("load", tag, *forces))

    def eleLoad(self, *args: int | float | str) -> None:
        self._lines.append(_ops_call("eleLoad", *args))

    def sp(self, tag: int, dof: int, value: float) -> None:
        self._lines.append(_ops_call("sp", tag, dof, value))

    def sp_hold(self, node: int, dof: int) -> None:
        # HOLD support (ADR 0052): pin the DOF at its current deformed
        # displacement, captured at runtime via ``ops.nodeDisp``, with
        # ``-const`` so the value is never scaled by the load factor.
        # Emitted as a raw line because the value is a runtime expression
        # (``ops.nodeDisp(...)``), not a literal that ``_ops_call`` formats.
        self._lines.append(
            f"ops.sp({node}, {dof}, ops.nodeDisp({node}, {dof}), '-const')"
        )

    # -- Recorders ----------------------------------------------------------

    def recorder(self, kind: str, *args: int | float | str) -> None:
        self._lines.append(_ops_call("recorder", kind, *args))

    def recorder_declaration_begin(
        self,
        *,
        declaration_name: str,
        record_name: str | None,
        category: str,
        components: tuple[str, ...],
        raw: tuple[str, ...] = (),
        pg: tuple[str, ...] = (),
        label: tuple[str, ...] = (),
        selection: tuple[str, ...] = (),
        ids: tuple[int, ...] | None = None,
        dt: float | None = None,
        n_steps: int | None = None,
        file_root: str = ".",
    ) -> None:
        """Phase 9 schema 2.3.0 declaration metadata — no-op for openseespy."""
        del (
            declaration_name, record_name, category, components, raw,
            pg, label, selection, ids, dt, n_steps, file_root,
        )

    def recorder_declaration_end(self) -> None:
        """Phase 9 schema 2.3.0 declaration metadata — no-op for openseespy."""

    # -- Analysis chain -----------------------------------------------------

    def constraints(self, c_type: str, *args: int | float | str) -> None:
        self._lines.append(_ops_call("constraints", c_type, *args))

    def numberer(self, n_type: str) -> None:
        self._lines.append(_ops_call("numberer", n_type))

    def system(self, s_type: str, *args: int | float | str) -> None:
        self._lines.append(_ops_call("system", s_type, *args))

    def test(self, t_type: str, *args: int | float | str) -> None:
        self._lines.append(_ops_call("test", t_type, *args))

    def algorithm(self, a_type: str, *args: int | float | str) -> None:
        self._lines.append(_ops_call("algorithm", a_type, *args))

    def integrator(self, i_type: str, *args: int | float | str) -> None:
        self._lines.append(_ops_call("integrator", i_type, *args))

    def analysis(self, a_type: str) -> None:
        self._lines.append(_ops_call("analysis", a_type))

    def analyze(self, *, steps: int, dt: float | None = None) -> int:
        if not self._step_hooks_registered:
            if dt is None:
                self._lines.append(_ops_call("analyze", steps))
            else:
                self._lines.append(_ops_call("analyze", steps, dt))
            return 0
        # Hook-wrapped form: Python for-loop with dispatcher calls.
        self._lines.append(f"for _apesees_i in range({int(steps)}):")
        prev_indent = self._lines.indent
        self._lines.indent = prev_indent + "    "
        self._lines.append("_apesees_call_before_step()")
        if dt is None:
            self._lines.append(_ops_call("analyze", 1))
        else:
            self._lines.append(_ops_call("analyze", 1, dt))
        self._lines.append("_apesees_call_after_step()")
        self._lines.indent = prev_indent
        return 0

    def eigen(
        self, num_modes: int, *, solver: str = "-genBandArpack",
    ) -> list[float]:
        self._lines.append(_ops_call("eigen", solver, num_modes))
        return []

    def profiler(self, *args: int | float | str) -> None:
        self._lines.append(_ops_call("profiler", *args))

    # -- Stress control (Phase SSI-1: initial_stress + ramping hooks) -------

    def addToParameter(
        self, tag: int, ele_tag: int, response: str,
    ) -> None:
        self._lines.append(
            _ops_call("addToParameter", tag, "element", ele_tag, response)
        )

    def step_hook_ramp(
        self,
        name: str,
        *,
        targets: tuple[tuple[int, float], ...],
        n_steps_to_full: float,
        phase: Literal["before", "after"] = "before",
    ) -> None:
        # 1. Dispatcher boilerplate (idempotent).
        if not self._hook_dispatcher_emitted:
            self._emit_hook_dispatcher_boilerplate()
            self._hook_dispatcher_emitted = True
        # 2. parameter declarations.
        for tag, _target in targets:
            self._lines.append(_ops_call("parameter", int(tag)))
        # 3. The per-step function body.
        self._emit_hook_ramp_function(name, targets, n_steps_to_full)
        # 4. Register with the appropriate dispatcher list.
        list_var = (
            "_apesees_before_step_hooks"
            if phase == "before"
            else "_apesees_after_step_hooks"
        )
        self._lines.append(f"{list_var}.append({name})")
        # 5. Flip flag so analyze() wraps.
        self._step_hooks_registered = True

    def _emit_hook_dispatcher_boilerplate(self) -> None:
        """Emit the once-per-deck hook dispatcher infrastructure."""
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append("# apeSees per-step hook dispatcher (Phase SSI-1)")
        self._lines.append("_apesees_before_step_hooks: list = []")
        self._lines.append("_apesees_after_step_hooks: list = []")
        self._lines.append("def _apesees_call_before_step() -> None:")
        self._lines.append("    for _f in _apesees_before_step_hooks:")
        self._lines.append("        _f()")
        self._lines.append("def _apesees_call_after_step() -> None:")
        self._lines.append("    for _f in _apesees_after_step_hooks:")
        self._lines.append("        _f()")
        self._lines.indent = prev_indent

    # -- Staged analysis (Phase SSI-2.A) ------------------------------------

    def stage_open(self, name: str) -> None:
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append(f"# === Stage: {name} ===")
        self._lines.indent = prev_indent

    def domain_change(self) -> None:
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append(_ops_call("domainChange"))
        self._lines.indent = prev_indent

    def stage_close(self) -> None:
        prev_indent = self._lines.indent
        self._lines.indent = ""
        # openseespy: ``ops.loadConst('-time', 0.0)`` matches the Tcl
        # ``loadConst -time 0.0`` semantics.
        self._lines.append(_ops_call("loadConst", "-time", 0.0))
        self._lines.append(_ops_call("wipeAnalysis"))
        if self._step_hooks_registered:
            self._lines.append("_apesees_before_step_hooks.clear()")
            self._lines.append("_apesees_after_step_hooks.clear()")
            self._step_hooks_registered = False
        self._lines.indent = prev_indent

    # -- Staged-analysis mutators (Phase SSI-2.E) ---------------------------

    def set_time(self, t: float) -> None:
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append(_ops_call("setTime", float(t)))
        self._lines.indent = prev_indent

    def set_creep(self, on: bool) -> None:
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append(_ops_call("setCreep", 1 if on else 0))
        self._lines.indent = prev_indent

    def reset(self) -> None:
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append(_ops_call("reset"))
        self._lines.indent = prev_indent

    def remove_sp(self, node: int, dof: int) -> None:
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append(_ops_call("remove", "sp", int(node), int(dof)))
        self._lines.indent = prev_indent

    def remove_element(self, tag: int) -> None:
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append(_ops_call("remove", "element", int(tag)))
        self._lines.indent = prev_indent

    def _emit_hook_ramp_function(
        self,
        name: str,
        targets: tuple[tuple[int, float], ...],
        n_steps_to_full: float,
    ) -> None:
        """Emit the per-step linear ramp function for one hook.

        Mirrors the Tcl proc: a module-level ``{name}_state`` dict
        carries the step counter and cumulative-value per parameter;
        each call advances the counter, recomputes the capped factor,
        and emits one ``ops.updateParameter`` per target.
        """
        prev_indent = self._lines.indent
        self._lines.indent = ""
        # State dict — declared at module level so the closure can
        # mutate it across calls.  Initial cumulative is 0.0 for every
        # parameter; the counter starts at 0.
        state_items = ", ".join(
            f"'cum_{int(tag)}': 0.0" for tag, _ in targets
        )
        self._lines.append(
            f"{name}_state: dict = {{'count': 0, {state_items}}}"
        )
        self._lines.append(f"def {name}() -> None:")
        self._lines.append(f"    {name}_state['count'] += 1")
        self._lines.append(
            f"    _factor = min({name}_state['count'] / "
            f"{repr(float(n_steps_to_full))}, 1.0)"
        )
        for tag, target in targets:
            self._lines.append(
                f"    _cur = {repr(float(target))} * _factor"
            )
            self._lines.append(
                f"    _delta = _cur - {name}_state['cum_{int(tag)}']"
            )
            self._lines.append(
                f"    ops.updateParameter({int(tag)}, _delta)"
            )
            self._lines.append(f"    {name}_state['cum_{int(tag)}'] = _cur")
        self._lines.indent = prev_indent

    # -- Partition emission scoping (ADR 0027, P4) --------------------------

    def partition_open(self, rank: int) -> None:
        """Open ``if getPID() == K:`` block; indent body 4 spaces.

        On the **first** call across the emitter's lifetime, emit the
        one-shot runtime shim wrapping
        ``from openseespy.opensees import getPID`` in a ``try /
        except ImportError`` with a 0-returning fallback — so a
        single-process Python (no OpenSeesMP) still runs the deck.
        """
        if not self._partition_shim_emitted:
            # Emit at indent 0 (the shim is global, not per-rank).
            prev_indent = self._lines.indent
            self._lines.indent = ""
            self._lines.append("try:")
            self._lines.append(
                "    from openseespy.opensees import getPID"
            )
            self._lines.append("except ImportError:")
            self._lines.append("    def getPID() -> int:")
            self._lines.append("        return 0")
            self._lines.indent = prev_indent
            self._partition_shim_emitted = True
        # Header line emitted at the outer indent.
        self._lines.append(f"if getPID() == {rank}:")
        # Indent subsequent emit calls one level deeper.
        self._lines.indent = self._lines.indent + "    "

    def partition_close(self) -> None:
        """Close the current per-rank block; emit trailing blank line.

        Python uses indentation, not a closing brace — ``partition_close``
        simply dedents and emits a blank separator line at the outer
        indent for readability.
        """
        if self._lines.indent.endswith("    "):
            self._lines.indent = self._lines.indent[:-4]
        self._lines.append("")

    # -- Partition runtime-conditional fallback (ADR 0027 INV-5) ------------

    def parallel_runtime_fallback_numberer(
        self, primary: str, fallback: str,
    ) -> None:
        """Emit a ``try / except`` wrapping ``ops.numberer(primary)``
        with a fallback ``ops.numberer(fallback)``.

        ``ParallelPlain`` only exists in OpenSeesMP; under single-process
        openseespy the call raises and the ``except`` branch falls back
        to ``RCM`` so the deck still runs.  Restores shim-consistency
        with :meth:`partition_open`'s ``getPID`` fallback (ADR 0027
        INV-5 amendment 2026-05-23).
        """
        self._lines.append(
            f"# {primary} only exists in OpenSeesMP; "
            f"fall back to {fallback} under single-process OpenSees."
        )
        self._lines.append("try:")
        self._lines.append(f"    {_ops_call('numberer', primary)}")
        self._lines.append("except Exception:")
        self._lines.append(f"    {_ops_call('numberer', fallback)}")

    def parallel_runtime_fallback_system(
        self, primary: str, fallback: str,
    ) -> None:
        """Emit a ``try / except`` wrapping ``ops.system(primary)``
        with a fallback ``ops.system(fallback)``.

        Mirror of :meth:`parallel_runtime_fallback_numberer`.
        """
        self._lines.append(
            f"# {primary} requires OpenSeesMP + MPI; "
            f"fall back to {fallback} under single-process OpenSees."
        )
        self._lines.append("try:")
        self._lines.append(f"    {_ops_call('system', primary)}")
        self._lines.append("except Exception:")
        self._lines.append(f"    {_ops_call('system', fallback)}")
