"""
TclEmitter — accumulates a Tcl deck as a list of strings.

The Tcl emitter is a pure text builder. Every Protocol method appends
one (or, for block-emit primitives, a few) lines to ``_lines``. The
deck is retrieved via :meth:`lines` once :meth:`emit` has driven the
full BuiltModel.

Tcl-specific dialect choices:

* Sections that take blocks (``Fiber``) emit
  ``section Fiber 1 -GJ 1.0e9 \\{`` with the opening brace; subsequent
  ``patch`` / ``fiber`` / ``layer`` lines indent inside the block;
  ``section_close`` emits ``\\}``.

* ``pattern_open`` is dispatched on the type token: ``Plain`` and
  ``MultiSupport`` open a block (``pattern Plain 1 1 \\{``); single-line
  patterns like ``UniformExcitation`` emit a single line and
  ``pattern_close`` is a no-op.

* Floats render with Python's ``repr(float)`` precision — enough digits
  to round-trip through the parser without rewriting the user's
  numbers.
"""
from __future__ import annotations

from typing import Any


__all__ = ["TclEmitter"]


#: Pattern type tokens that open a Tcl block (``\\{`` ... ``\\}``). Other
#: pattern type tokens emit a single line and ``pattern_close`` is a no-op.
_BLOCK_PATTERNS: tuple[str, ...] = ("Plain", "MultiSupport")


def _fmt_value(v: Any) -> str:
    """Render one positional argument for Tcl.

    Strings pass through unchanged (no quoting — OpenSees Tcl tokens
    don't normally need it for our vocabulary). Booleans are coerced
    to ``1`` / ``0`` (OpenSees doesn't speak Python ``True``).
    Integers and floats use their ``repr`` (which preserves enough
    digits for floats to round-trip).
    """
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, str):
        return v
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    # Fallback — should not happen for the typed-emit boundary.
    return str(v)


def _join(*parts: Any) -> str:
    """Render a Tcl line from ``parts`` separated by single spaces."""
    return " ".join(_fmt_value(p) for p in parts)


class TclEmitter:
    """Accumulates an OpenSees Tcl deck as a list of strings.

    Construct with no arguments; drive it through ``BuiltModel.emit``;
    retrieve the deck via :meth:`lines`.

    The class also exposes :meth:`preamble` to inject a leading comment
    line. Most users will rely on the default banner emitted by
    ``__init__``.
    """

    def __init__(self) -> None:
        self._lines: list[str] = [
            "# auto-generated by apeGmsh.opensees; do not edit by hand",
        ]
        # Tracks the type token of the currently-open pattern (for
        # pattern_close to decide whether to emit ``\\}``). None means
        # no pattern open or the open pattern is single-line.
        self._open_block_pattern: str | None = None

    # -- Output --------------------------------------------------------------

    def lines(self) -> list[str]:
        """Return a copy of the accumulated Tcl lines."""
        return list(self._lines)

    def preamble(self, text: str) -> None:
        """Insert ``text`` as a leading comment line. Idempotent."""
        self._lines.insert(0, f"# {text}")

    # -- Model ---------------------------------------------------------------

    def model(self, *, ndm: int, ndf: int) -> None:
        self._lines.append(f"model BasicBuilder -ndm {ndm} -ndf {ndf}")

    def node(self, tag: int, *coords: float) -> None:
        self._lines.append(_join("node", tag, *coords))

    def fix(self, tag: int, *dofs: int) -> None:
        self._lines.append(_join("fix", tag, *dofs))

    def mass(self, tag: int, *values: float) -> None:
        self._lines.append(_join("mass", tag, *values))

    # -- Constitutive --------------------------------------------------------

    def uniaxialMaterial(
        self, mat_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(_join("uniaxialMaterial", mat_type, tag, *params))

    def nDMaterial(
        self, mat_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(_join("nDMaterial", mat_type, tag, *params))

    def section(
        self, sec_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(_join("section", sec_type, tag, *params))

    def geomTransf(self, t_type: str, tag: int, *vec: float) -> None:
        self._lines.append(_join("geomTransf", t_type, tag, *vec))

    # -- Sections that take blocks (Fiber) ----------------------------------

    def section_open(
        self, sec_type: str, tag: int, *params: float | str,
    ) -> None:
        # Open the block — Tcl's curly brace must be the LAST token on
        # the line for the parser to consume the body.
        head = _join("section", sec_type, tag, *params)
        self._lines.append(f"{head} {{")

    def section_close(self) -> None:
        self._lines.append("}")

    def patch(self, kind: str, *args: int | float) -> None:
        self._lines.append("    " + _join("patch", kind, *args))

    def fiber(
        self, y: float, z: float, area: float, mat_tag: int,
    ) -> None:
        self._lines.append("    " + _join("fiber", y, z, area, mat_tag))

    def layer(self, kind: str, *args: int | float) -> None:
        self._lines.append("    " + _join("layer", kind, *args))

    # -- Beam integration rules ---------------------------------------------

    def beamIntegration(
        self, rule_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_join("beamIntegration", rule_type, tag, *args))

    # -- Topology ------------------------------------------------------------

    def element(
        self, ele_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_join("element", ele_type, tag, *args))

    # -- Time series --------------------------------------------------------

    def timeSeries(
        self, ts_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_join("timeSeries", ts_type, tag, *args))

    # -- Patterns -----------------------------------------------------------

    def pattern_open(
        self, p_type: str, tag: int, *args: int | float | str,
    ) -> None:
        head = _join("pattern", p_type, tag, *args)
        if p_type in _BLOCK_PATTERNS:
            self._lines.append(f"{head} {{")
            self._open_block_pattern = p_type
        else:
            self._lines.append(head)
            self._open_block_pattern = None

    def pattern_close(self) -> None:
        if self._open_block_pattern is not None:
            self._lines.append("}")
            self._open_block_pattern = None
        # else: single-line pattern; pattern_close is a no-op.

    def load(self, tag: int, *forces: float) -> None:
        # Inside a Plain pattern: indent for readability.
        prefix = "    " if self._open_block_pattern else ""
        self._lines.append(prefix + _join("load", tag, *forces))

    def eleLoad(self, *args: int | float | str) -> None:
        prefix = "    " if self._open_block_pattern else ""
        self._lines.append(prefix + _join("eleLoad", *args))

    def sp(self, tag: int, dof: int, value: float) -> None:
        prefix = "    " if self._open_block_pattern else ""
        self._lines.append(prefix + _join("sp", tag, dof, value))

    # -- Recorders ----------------------------------------------------------

    def recorder(self, kind: str, *args: int | float | str) -> None:
        self._lines.append(_join("recorder", kind, *args))

    def recorder_declaration_begin(
        self,
        *,
        declaration_name: str,
        record_name: str | None,
        category: str,
        components: tuple[str, ...],
        raw: tuple[str, ...] = (),
        pg: tuple[str, ...] = (),
        label: tuple[str, ...] = (),
        selection: tuple[str, ...] = (),
        ids: tuple[int, ...] | None = None,
        dt: float | None = None,
        n_steps: int | None = None,
        file_root: str = ".",
    ) -> None:
        """Phase 9 schema 2.3.0 declaration metadata — no-op for Tcl."""
        del (
            declaration_name, record_name, category, components, raw,
            pg, label, selection, ids, dt, n_steps, file_root,
        )

    def recorder_declaration_end(self) -> None:
        """Phase 9 schema 2.3.0 declaration metadata — no-op for Tcl."""

    # -- Analysis chain -----------------------------------------------------

    def constraints(self, c_type: str, *args: float) -> None:
        self._lines.append(_join("constraints", c_type, *args))

    def numberer(self, n_type: str) -> None:
        self._lines.append(_join("numberer", n_type))

    def system(self, s_type: str, *args: int | float | str) -> None:
        self._lines.append(_join("system", s_type, *args))

    def test(self, t_type: str, *args: int | float | str) -> None:
        self._lines.append(_join("test", t_type, *args))

    def algorithm(self, a_type: str, *args: int | float | str) -> None:
        self._lines.append(_join("algorithm", a_type, *args))

    def integrator(self, i_type: str, *args: int | float | str) -> None:
        self._lines.append(_join("integrator", i_type, *args))

    def analysis(self, a_type: str) -> None:
        self._lines.append(_join("analysis", a_type))

    def analyze(self, *, steps: int, dt: float | None = None) -> int:
        if dt is None:
            self._lines.append(f"analyze {steps}")
        else:
            self._lines.append(_join("analyze", steps, dt))
        return 0
