"""
TclEmitter — accumulates a Tcl deck as a list of strings.

The Tcl emitter is a pure text builder. Every Protocol method appends
one (or, for block-emit primitives, a few) lines to ``_lines``. The
deck is retrieved via :meth:`lines` once :meth:`emit` has driven the
full BuiltModel.

Tcl-specific dialect choices:

* Sections that take blocks (``Fiber``) emit
  ``section Fiber 1 -GJ 1.0e9 \\{`` with the opening brace; subsequent
  ``patch`` / ``fiber`` / ``layer`` lines indent inside the block;
  ``section_close`` emits ``\\}``.

* ``pattern_open`` is dispatched on the type token: ``Plain`` and
  ``MultiSupport`` open a block (``pattern Plain 1 1 \\{``); single-line
  patterns like ``UniformExcitation`` emit a single line and
  ``pattern_close`` is a no-op.

* Floats render with Python's ``repr(float)`` precision — enough digits
  to round-trip through the parser without rewriting the user's
  numbers.
"""
from __future__ import annotations

from typing import Any, Literal


__all__ = ["TclEmitter"]


#: Pattern type tokens that open a Tcl block (``\\{`` ... ``\\}``). Other
#: pattern type tokens emit a single line and ``pattern_close`` is a no-op.
_BLOCK_PATTERNS: tuple[str, ...] = ("Plain", "MultiSupport")


class _LineBuf(list[str]):
    """Line buffer with an optional partition-indent prefix.

    Behaves as a plain ``list[str]`` for ``insert``, iteration, slicing,
    and the ``lines()`` copy-out. When ``indent`` is non-empty, every
    ``append(line)`` prepends ``indent`` to ``line`` before storing.
    This keeps the existing ``self._lines.append(...)`` call sites in
    :class:`TclEmitter` working unchanged while
    ``partition_open(K)`` / ``partition_close()`` toggle the indent.
    """

    __slots__ = ("indent",)

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.indent: str = ""

    def append(self, line: str) -> None:  # type: ignore[override]
        if self.indent:
            super().append(self.indent + line)
        else:
            super().append(line)


def _fmt_value(v: Any) -> str:
    """Render one positional argument for Tcl.

    Strings pass through unchanged (no quoting — OpenSees Tcl tokens
    don't normally need it for our vocabulary). Booleans are coerced
    to ``1`` / ``0`` (OpenSees doesn't speak Python ``True``).
    Integers and floats use their ``repr`` (which preserves enough
    digits for floats to round-trip).
    """
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, str):
        return v
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    # Fallback — should not happen for the typed-emit boundary.
    return str(v)


def _join(*parts: Any) -> str:
    """Render a Tcl line from ``parts`` separated by single spaces."""
    return " ".join(_fmt_value(p) for p in parts)


class TclEmitter:
    """Accumulates an OpenSees Tcl deck as a list of strings.

    Construct with no arguments; drive it through ``BuiltModel.emit``;
    retrieve the deck via :meth:`lines`.

    The class also exposes :meth:`preamble` to inject a leading comment
    line. Most users will rely on the default banner emitted by
    ``__init__``.
    """

    def __init__(self) -> None:
        # ``_lines`` is a :class:`_LineBuf` so ``partition_open`` can
        # toggle a per-rank indent without every ``append`` call site
        # needing to know. All existing primitives keep calling
        # ``self._lines.append(...)`` unchanged.
        self._lines: _LineBuf = _LineBuf([
            "# auto-generated by apeGmsh.opensees; do not edit by hand",
        ])
        # Tracks the type token of the currently-open pattern (for
        # pattern_close to decide whether to emit ``\\}``). None means
        # no pattern open or the open pattern is single-line.
        self._open_block_pattern: str | None = None
        # Partition-emission state (ADR 0027 / P4). ``_in_partition``
        # is True between ``partition_open`` and ``partition_close``;
        # ``_partition_shim_emitted`` flips on the first
        # ``partition_open`` call so the ``proc getPID`` fallback is
        # emitted exactly once. Per-rank content is indented one level
        # (4 spaces) so the closing ``\\}`` lines up with the opening
        # ``if {[getPID] == K}``.
        self._partition_shim_emitted: bool = False
        # Step-hook state (Phase SSI-1).  ``_step_hooks_registered``
        # flips to True the first time ``step_hook_ramp`` runs and is
        # checked by ``analyze`` to decide whether to wrap the analyze
        # loop with hook-dispatcher calls.
        # ``_hook_dispatcher_emitted`` toggles on the first
        # ``step_hook_ramp`` call so the dispatcher boilerplate (list
        # variables + dispatcher procs) emits exactly once.
        self._step_hooks_registered: bool = False
        self._hook_dispatcher_emitted: bool = False

    # -- Output --------------------------------------------------------------

    def lines(self) -> list[str]:
        """Return a copy of the accumulated Tcl lines."""
        return list(self._lines)

    def preamble(self, text: str) -> None:
        """Insert ``text`` as a leading comment line. Idempotent."""
        self._lines.insert(0, f"# {text}")

    # -- Model ---------------------------------------------------------------

    def model(self, *, ndm: int, ndf: int) -> None:
        self._lines.append(f"model BasicBuilder -ndm {ndm} -ndf {ndf}")

    def node(
        self, tag: int, *coords: float, ndf: int | None = None,
    ) -> None:
        if ndf is None:
            self._lines.append(_join("node", tag, *coords))
        else:
            # Per-node ``-ndf`` override (used for 6-DOF phantom nodes in
            # otherwise 3-DOF models; ADR 0022 INV-3).
            self._lines.append(
                _join("node", tag, *coords, "-ndf", ndf)
            )

    def fix(self, tag: int, *dofs: int) -> None:
        self._lines.append(_join("fix", tag, *dofs))

    def mass(self, tag: int, *values: float) -> None:
        self._lines.append(_join("mass", tag, *values))

    # -- MP constraints (ADR 0022, Phase 7b) -----------------------------

    def equalDOF(self, master: int, slave: int, *dofs: int) -> None:
        self._lines.append(_join("equalDOF", master, slave, *dofs))

    def rigidLink(self, kind: str, master: int, slave: int) -> None:
        # ``rigidLink {beam|bar} $master $slave`` — kind is unquoted.
        self._lines.append(_join("rigidLink", kind, master, slave))

    def rigidDiaphragm(
        self, perp_dir: int, master: int, *slaves: int,
    ) -> None:
        self._lines.append(
            _join("rigidDiaphragm", perp_dir, master, *slaves)
        )

    def embeddedNode(
        self, ele_tag: int, cnode: int,
        *args: int | float,
    ) -> None:
        # ASDEmbeddedNodeElement covers tie / tied_contact / mortar /
        # embedded surface-coupling primitives (ADR 0022).
        self._lines.append(
            _join(
                "element", "ASDEmbeddedNodeElement",
                ele_tag, cnode, *args,
            )
        )

    def mp_constraint_comment(self, name: str) -> None:
        # Round-trips the user's declaration label into the deck (INV-2).
        self._lines.append(f"# {name}")

    # -- Regions -------------------------------------------------------------

    def region(self, tag: int, *args: int | float | str) -> None:
        self._lines.append(_join("region", tag, *args))

    # -- Constitutive --------------------------------------------------------

    def uniaxialMaterial(
        self, mat_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(_join("uniaxialMaterial", mat_type, tag, *params))

    def nDMaterial(
        self, mat_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(_join("nDMaterial", mat_type, tag, *params))

    def section(
        self, sec_type: str, tag: int, *params: float | str,
    ) -> None:
        self._lines.append(_join("section", sec_type, tag, *params))

    def geomTransf(self, t_type: str, tag: int, *vec: float) -> None:
        self._lines.append(_join("geomTransf", t_type, tag, *vec))

    # -- Sections that take blocks (Fiber) ----------------------------------

    def section_open(
        self, sec_type: str, tag: int, *params: float | str,
    ) -> None:
        # Open the block — Tcl's curly brace must be the LAST token on
        # the line for the parser to consume the body.
        head = _join("section", sec_type, tag, *params)
        self._lines.append(f"{head} {{")

    def section_close(self) -> None:
        self._lines.append("}")

    def patch(self, kind: str, *args: int | float) -> None:
        self._lines.append("    " + _join("patch", kind, *args))

    def fiber(
        self, y: float, z: float, area: float, mat_tag: int,
    ) -> None:
        self._lines.append("    " + _join("fiber", y, z, area, mat_tag))

    def layer(self, kind: str, *args: int | float) -> None:
        self._lines.append("    " + _join("layer", kind, *args))

    # -- Beam integration rules ---------------------------------------------

    def beamIntegration(
        self, rule_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_join("beamIntegration", rule_type, tag, *args))

    # -- Topology ------------------------------------------------------------

    def element(
        self, ele_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_join("element", ele_type, tag, *args))

    # -- Time series --------------------------------------------------------

    def timeSeries(
        self, ts_type: str, tag: int, *args: int | float | str,
    ) -> None:
        self._lines.append(_join("timeSeries", ts_type, tag, *args))

    # -- Patterns -----------------------------------------------------------

    def pattern_open(
        self, p_type: str, tag: int, *args: int | float | str,
    ) -> None:
        head = _join("pattern", p_type, tag, *args)
        if p_type in _BLOCK_PATTERNS:
            self._lines.append(f"{head} {{")
            self._open_block_pattern = p_type
        else:
            self._lines.append(head)
            self._open_block_pattern = None

    def pattern_close(self) -> None:
        if self._open_block_pattern is not None:
            self._lines.append("}")
            self._open_block_pattern = None
        # else: single-line pattern; pattern_close is a no-op.

    def load(self, tag: int, *forces: float) -> None:
        # Inside a Plain pattern: indent for readability.
        prefix = "    " if self._open_block_pattern else ""
        self._lines.append(prefix + _join("load", tag, *forces))

    def eleLoad(self, *args: int | float | str) -> None:
        prefix = "    " if self._open_block_pattern else ""
        self._lines.append(prefix + _join("eleLoad", *args))

    def sp(self, tag: int, dof: int, value: float) -> None:
        prefix = "    " if self._open_block_pattern else ""
        self._lines.append(prefix + _join("sp", tag, dof, value))

    # -- Recorders ----------------------------------------------------------

    def recorder(self, kind: str, *args: int | float | str) -> None:
        self._lines.append(_join("recorder", kind, *args))

    def recorder_declaration_begin(
        self,
        *,
        declaration_name: str,
        record_name: str | None,
        category: str,
        components: tuple[str, ...],
        raw: tuple[str, ...] = (),
        pg: tuple[str, ...] = (),
        label: tuple[str, ...] = (),
        selection: tuple[str, ...] = (),
        ids: tuple[int, ...] | None = None,
        dt: float | None = None,
        n_steps: int | None = None,
        file_root: str = ".",
    ) -> None:
        """Phase 9 schema 2.3.0 declaration metadata — no-op for Tcl."""
        del (
            declaration_name, record_name, category, components, raw,
            pg, label, selection, ids, dt, n_steps, file_root,
        )

    def recorder_declaration_end(self) -> None:
        """Phase 9 schema 2.3.0 declaration metadata — no-op for Tcl."""

    # -- Analysis chain -----------------------------------------------------

    def constraints(self, c_type: str, *args: float) -> None:
        self._lines.append(_join("constraints", c_type, *args))

    def numberer(self, n_type: str) -> None:
        self._lines.append(_join("numberer", n_type))

    def system(self, s_type: str, *args: int | float | str) -> None:
        self._lines.append(_join("system", s_type, *args))

    def test(self, t_type: str, *args: int | float | str) -> None:
        self._lines.append(_join("test", t_type, *args))

    def algorithm(self, a_type: str, *args: int | float | str) -> None:
        self._lines.append(_join("algorithm", a_type, *args))

    def integrator(self, i_type: str, *args: int | float | str) -> None:
        self._lines.append(_join("integrator", i_type, *args))

    def analysis(self, a_type: str) -> None:
        self._lines.append(_join("analysis", a_type))

    def analyze(self, *, steps: int, dt: float | None = None) -> int:
        if not self._step_hooks_registered:
            if dt is None:
                self._lines.append(f"analyze {steps}")
            else:
                self._lines.append(_join("analyze", steps, dt))
            return 0
        # Hook-wrapped form: for-loop with dispatcher calls per step.
        # We use a private loop variable name to avoid clashing with
        # anything the user might define in their own Tcl.
        self._lines.append(
            f"for {{set _apesees_i 0}} {{$_apesees_i < {steps}}} "
            f"{{incr _apesees_i}} {{"
        )
        prev_indent = self._lines.indent
        self._lines.indent = prev_indent + "    "
        self._lines.append("_apesees_call_before_step")
        if dt is None:
            self._lines.append("analyze 1")
        else:
            self._lines.append(_join("analyze", 1, dt))
        self._lines.append("_apesees_call_after_step")
        self._lines.indent = prev_indent
        self._lines.append("}")
        return 0

    def eigen(
        self, num_modes: int, *, solver: str = "-genBandArpack",
    ) -> list[float]:
        self._lines.append(_join("eigen", solver, num_modes))
        return []

    # -- Stress control (Phase SSI-1: initial_stress + ramping hooks) -------

    def addToParameter(
        self, tag: int, ele_tag: int, response: str,
    ) -> None:
        self._lines.append(
            _join("addToParameter", tag, "element", ele_tag, response)
        )

    def step_hook_ramp(
        self,
        name: str,
        *,
        targets: tuple[tuple[int, float], ...],
        n_steps_to_full: float,
        phase: Literal["before", "after"] = "before",
    ) -> None:
        # 1. Dispatcher boilerplate (idempotent — emitted on first call).
        if not self._hook_dispatcher_emitted:
            self._emit_hook_dispatcher_boilerplate()
            self._hook_dispatcher_emitted = True
        # 2. parameter declarations (one per ramped component).  These
        # are global — emit at the outer indent so partition_open does
        # NOT scope them per-rank.
        for tag, _target in targets:
            self._lines.append(_join("parameter", int(tag)))
        # 3. The per-step proc body.  Uses a Tcl array keyed by a name
        # that includes the hook name (so multiple ramps don't clash).
        self._emit_hook_ramp_proc(name, targets, n_steps_to_full)
        # 4. Register with the appropriate dispatcher list.
        list_var = (
            "_apesees_before_step_hooks"
            if phase == "before"
            else "_apesees_after_step_hooks"
        )
        self._lines.append(f"lappend {list_var} {name}")
        # 5. Flip the flag so future analyze() calls know to wrap.
        self._step_hooks_registered = True

    def _emit_hook_dispatcher_boilerplate(self) -> None:
        """Emit the once-per-deck hook dispatcher infrastructure.

        Mirrors STKO's ``STKO_CALL_OnBeforeAnalyze`` pattern but with
        apeSees-prefixed names so emitted decks don't collide with
        hand-written STKO blocks.
        """
        # Emit at indent 0 (the dispatcher is global, not per-rank).
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append(
            "# apeSees per-step hook dispatcher (Phase SSI-1)"
        )
        self._lines.append("set _apesees_before_step_hooks {}")
        self._lines.append("set _apesees_after_step_hooks {}")
        self._lines.append("proc _apesees_call_before_step {} {")
        self._lines.append(
            "    global _apesees_before_step_hooks"
        )
        self._lines.append(
            "    foreach _f $_apesees_before_step_hooks { $_f }"
        )
        self._lines.append("}")
        self._lines.append("proc _apesees_call_after_step {} {")
        self._lines.append("    global _apesees_after_step_hooks")
        self._lines.append(
            "    foreach _f $_apesees_after_step_hooks { $_f }"
        )
        self._lines.append("}")
        self._lines.indent = prev_indent

    # -- Staged analysis (Phase SSI-2.A) ------------------------------------

    def stage_open(self, name: str) -> None:
        # Human-readable banner.  Emitted at the outer indent so it
        # remains visible even inside partition-open blocks.
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append(f"# === Stage: {name} ===")
        self._lines.indent = prev_indent

    def domain_change(self) -> None:
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append("domainChange")
        self._lines.indent = prev_indent

    def stage_close(self) -> None:
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append("loadConst -time 0.0")
        self._lines.append("wipeAnalysis")
        if self._step_hooks_registered:
            # Clear the dispatcher lists so the next stage's hooks
            # don't inherit this stage's procs.  Proc bodies persist
            # but are unreachable until a future ``lappend`` puts
            # them back into the list.
            self._lines.append("set _apesees_before_step_hooks {}")
            self._lines.append("set _apesees_after_step_hooks {}")
            # Reset the "are hooks live?" flag so the next stage's
            # ``analyze`` emits a bare ``analyze N`` line UNLESS that
            # stage also registers a ramp (the orchestrator emits
            # ramp registrations BEFORE the next analyze).
            self._step_hooks_registered = False
        self._lines.indent = prev_indent

    def _emit_hook_ramp_proc(
        self,
        name: str,
        targets: tuple[tuple[int, float], ...],
        n_steps_to_full: float,
    ) -> None:
        """Emit the per-step linear ramp procedure body for one hook.

        The proc tracks a private Tcl array ``${name}_state`` carrying
        a step counter plus one cumulative-value entry per parameter.
        Each call advances the counter, recomputes the factor (capped
        at 1.0), and emits one ``updateParameter $tag $delta`` per
        target where ``$delta = target * factor - previous_cumulative``.
        """
        # Emit at indent 0 — procs are global definitions.
        prev_indent = self._lines.indent
        self._lines.indent = ""
        self._lines.append(f"proc {name} {{}} {{")
        self._lines.append(f"    global {name}_state")
        # First-call initialization of state array.
        self._lines.append(f"    if {{![info exists {name}_state(count)]}} {{")
        self._lines.append(f"        set {name}_state(count) 0")
        for tag, _target in targets:
            self._lines.append(
                f"        set {name}_state(cum_{int(tag)}) 0.0"
            )
        self._lines.append("    }")
        # Advance counter, compute capped factor.
        self._lines.append(
            f"    set {name}_state(count) "
            f"[expr {{${name}_state(count) + 1}}]"
        )
        self._lines.append(
            f"    set _factor [expr "
            f"{{${name}_state(count) / {repr(float(n_steps_to_full))}}}]"
        )
        self._lines.append("    if {$_factor > 1.0} { set _factor 1.0 }")
        # One updateParameter per target — delta = current - previous.
        for tag, target in targets:
            self._lines.append(
                f"    set _cur [expr {{{repr(float(target))} * $_factor}}]"
            )
            self._lines.append(
                f"    set _delta "
                f"[expr {{$_cur - ${name}_state(cum_{int(tag)})}}]"
            )
            self._lines.append(f"    updateParameter {int(tag)} $_delta")
            self._lines.append(
                f"    set {name}_state(cum_{int(tag)}) $_cur"
            )
        self._lines.append("}")
        self._lines.indent = prev_indent

    # -- Partition emission scoping (ADR 0027, P4) --------------------------

    def partition_open(self, rank: int) -> None:
        """Open ``if {[getPID] == K} \\{ ... \\}`` block; indent body 4 spaces.

        On the **first** call across the emitter's lifetime, emit the
        one-shot runtime shim ``if {[info procs getPID] == ""} { proc
        getPID {} { return 0 } }`` so single-process OpenSees (no
        OpenSeesMP loaded) still parses and runs the deck — the
        fallback returns 0 so only the rank-0 block executes.
        """
        if not self._partition_shim_emitted:
            # Emit at indent 0 (the shim is global, not per-rank).
            prev_indent = self._lines.indent
            self._lines.indent = ""
            self._lines.append(
                "if {[info procs getPID] == \"\"} "
                "{ proc getPID {} { return 0 } }"
            )
            self._lines.indent = prev_indent
            self._partition_shim_emitted = True
        # Header line is emitted at the **outer** indent (not nested
        # inside the partition's own indent).
        self._lines.append(
            "if {[getPID] == " + str(rank) + "} {"
        )
        # Indent subsequent emit calls one level deeper.
        self._lines.indent = self._lines.indent + "    "

    def partition_close(self) -> None:
        """Close the current per-rank block; emit trailing blank line."""
        # Drop one indent level.
        if self._lines.indent.endswith("    "):
            self._lines.indent = self._lines.indent[:-4]
        # Closing brace and trailing blank line at the outer indent.
        self._lines.append("}")
        self._lines.append("")

    # -- Partition runtime-conditional fallback (ADR 0027 INV-5) ------------

    def parallel_runtime_fallback_numberer(
        self, primary: str, fallback: str,
    ) -> None:
        """Emit ``if {[catch {numberer $primary} _err]} { numberer $fallback }``.

        ``ParallelPlain`` (the typical primary) only exists in
        OpenSeesMP; under single-process OpenSees the ``numberer``
        command errors and the Tcl ``catch`` swallows it so the
        fallback (typically ``RCM``) runs instead.  Restores
        shim-consistency with :meth:`partition_open`'s ``proc getPID``
        fallback (ADR 0027 INV-5 amendment 2026-05-23).
        """
        self._lines.append(
            f"# {primary} only exists in OpenSeesMP; "
            f"fall back to {fallback} under single-process OpenSees."
        )
        self._lines.append(
            f"if {{[catch {{numberer {primary}}} _err]}} "
            f"{{ numberer {fallback} }}"
        )

    def parallel_runtime_fallback_system(
        self, primary: str, fallback: str,
    ) -> None:
        """Emit ``if {[catch {system $primary} _err]} { system $fallback }``.

        Mirror of :meth:`parallel_runtime_fallback_numberer` — the
        primary (``Mumps``) requires OpenSeesMP + MPI; the fallback
        (``UmfPack``) lets the deck still parse and run under
        single-process OpenSees.
        """
        self._lines.append(
            f"# {primary} requires OpenSeesMP + MPI; "
            f"fall back to {fallback} under single-process OpenSees."
        )
        self._lines.append(
            f"if {{[catch {{system {primary}}} _err]}} "
            f"{{ system {fallback} }}"
        )
