"""``SectionSweepDef`` — a sequence of :class:`SectionCutDef` sharing
one element filter.

The natural data structure for story-shear-vs-elevation profiles,
soil-column depth scans, and through-thickness force distributions.
Pure composition over :class:`SectionCutDef`: no new validation, no
new geometry, no new dependencies.

Convention: all cuts in a sweep share the same ``elements_pg`` and
the same ``side``. Per-plane filters and sides are a niche case;
build a ``list[SectionCutDef]`` manually if you need them.

Plane locators
--------------
For axis-aligned sweeps (the common case — horizontal grid, vertical
grid), :meth:`SectionSweepDef.plane_locators` returns one scalar
coordinate per plane (the z for horizontal cuts, x or y for vertical
cuts). Handy for the matplotlib idiom::

    ax.plot(env["Fz_peak_abs"], sweep.plane_locators("z"), "o-")
"""
from __future__ import annotations

import gzip
import pickle
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Iterable, Iterator, Sequence

import numpy as np

from ._defs import SectionCutDef, Side, Vec3

if TYPE_CHECKING:
    from apeGmsh.mesh.FEMData import FEMData


@dataclass(frozen=True)
class SectionSweepDef:
    """A frozen sequence of :class:`SectionCutDef` instances.

    Construct via :meth:`from_planes`, :meth:`from_horizontal_grid`,
    or :meth:`from_pg_pattern`. Iterates in plane order; index
    accessors mirror :class:`STKO_to_python.cuts.SectionSweep`.
    """

    cuts: tuple[SectionCutDef, ...]

    def __post_init__(self) -> None:
        cuts_tuple = tuple(self.cuts)
        object.__setattr__(self, "cuts", cuts_tuple)

    # ------------------------------------------------------------------ #
    # Construction
    # ------------------------------------------------------------------ #
    @classmethod
    def from_planes(
        cls,
        *,
        planes: Sequence[tuple[Vec3, Vec3]],
        elements_pg: str,
        fem: "FEMData",
        model_h5: str | Path,
        side: Side = "positive",
        label_prefix: str | None = None,
    ) -> "SectionSweepDef":
        """Sweep with an explicit list of ``(point, normal)`` planes.

        Each plane shares the same ``elements_pg`` filter. If
        ``label_prefix`` is set, each cut gets a label
        ``f"{label_prefix}[{i}]"``; otherwise no label is set.
        """
        cuts = tuple(
            SectionCutDef.from_plane_and_pg(
                plane=plane,
                elements_pg=elements_pg,
                fem=fem,
                model_h5=model_h5,
                side=side,
                label=(
                    f"{label_prefix}[{i}]"
                    if label_prefix is not None else None
                ),
            )
            for i, plane in enumerate(planes)
        )
        return cls(cuts=cuts)

    @classmethod
    def from_horizontal_grid(
        cls,
        *,
        elevations: Iterable[float],
        elements_pg: str,
        fem: "FEMData",
        model_h5: str | Path,
        side: Side = "positive",
        label_prefix: str | None = None,
    ) -> "SectionSweepDef":
        """Sweep of horizontal cuts at each elevation in ``elevations``.

        Convenience over :meth:`from_planes` for the most common
        case — building-level story-shear profiles.
        """
        from ._planes import plane_horizontal
        planes = [plane_horizontal(z) for z in elevations]
        return cls.from_planes(
            planes=planes,
            elements_pg=elements_pg,
            fem=fem,
            model_h5=model_h5,
            side=side,
            label_prefix=label_prefix,
        )

    @classmethod
    def from_pg_pattern(
        cls,
        *,
        plane_pgs: Sequence[str],
        elements_pg: str,
        fem: "FEMData",
        model_h5: str | Path,
        side: Side = "positive",
        normal_hint: Iterable[float] | np.ndarray | None = None,
        tol: float = 1e-6,
        with_bounding: bool = False,
    ) -> "SectionSweepDef":
        """Sweep where each plane is derived from a named physical group.

        ``plane_pgs`` is consumed in order; each name resolves to one
        cut. Use this for "I named every diaphragm in my model and
        want a story-shear sweep across all of them" — no manual
        z-coords required.

        Each cut keeps the auto-label generated by
        :meth:`SectionCutDef.from_planar_pg` so the originating PG
        name shows up in plot legends.

        ``with_bounding=True`` derives a convex bounding polygon from
        each ``plane_pg``'s nodes (one polygon per cut). See
        :func:`bounding_polygon_from_physical_surface`.
        """
        cuts = tuple(
            SectionCutDef.from_planar_pg(
                plane_pg=pg,
                elements_pg=elements_pg,
                fem=fem,
                model_h5=model_h5,
                side=side,
                normal_hint=normal_hint,
                tol=tol,
                with_bounding=with_bounding,
            )
            for pg in plane_pgs
        )
        return cls(cuts=cuts)

    @classmethod
    def from_pg_glob(
        cls,
        *,
        pattern: str,
        elements_pg: str,
        fem: "FEMData",
        model_h5: str | Path,
        side: Side = "positive",
        normal_hint: Iterable[float] | np.ndarray | None = None,
        tol: float = 1e-6,
        with_bounding: bool = False,
        dim: int = 2,
    ) -> "SectionSweepDef":
        """Sweep across every physical group whose name matches ``pattern``.

        Resolves the glob against ``fem.nodes.physical.names(dim=dim)``
        (default ``dim=2`` — planar surface PGs). Matched names are
        sorted with a natural-numeric key so ``"diaphragm-2"`` comes
        before ``"diaphragm-10"``. The sorted list is then handed to
        :meth:`from_pg_pattern`.

        Parameters
        ----------
        pattern:
            ``fnmatch`` glob, e.g. ``"diaphragm-*"`` or ``"story[1-9]"``.
            Matching is case-sensitive.
        elements_pg, fem, model_h5, side, normal_hint, tol, with_bounding:
            Pass-through to :meth:`from_pg_pattern`.
        dim:
            Dimension filter when enumerating PGs from ``fem``. Default
            ``2`` (surface PGs — the common case for cut planes).
            Pass ``-1`` to match across all dimensions.

        Raises
        ------
        ValueError
            No PG names match the pattern.
        """
        import fnmatch
        import re

        all_names = fem.nodes.physical.names(dim=dim)
        matched = [n for n in all_names if fnmatch.fnmatchcase(n, pattern)]
        if not matched:
            raise ValueError(
                f"No physical groups matched glob {pattern!r} "
                f"(dim={dim}). Available: {sorted(all_names)[:10]}"
                + ("…" if len(all_names) > 10 else "")
            )

        def _natural_key(s: str) -> list[object]:
            # 'diaphragm-2' → ['diaphragm-', 2, ''] so numeric runs sort
            # numerically. Strings compare to strings (post-split parts
            # always alternate text/digit/text), so the heterogeneous
            # list comparison is safe.
            return [
                int(p) if p.isdigit() else p
                for p in re.split(r"(\d+)", s)
            ]

        sorted_names = sorted(matched, key=_natural_key)
        return cls.from_pg_pattern(
            plane_pgs=sorted_names,
            elements_pg=elements_pg,
            fem=fem,
            model_h5=model_h5,
            side=side,
            normal_hint=normal_hint,
            tol=tol,
            with_bounding=with_bounding,
        )

    # ------------------------------------------------------------------ #
    # STKO_to_python interop
    # ------------------------------------------------------------------ #
    def to_specs(self) -> list:
        """Convert every cut to a STKO ``SectionCutSpec``.

        Lazy-imports STKO_to_python via ``SectionCutDef.to_spec``.
        Raises ``ImportError`` if STKO_to_python is not installed.
        """
        return [cut.to_spec() for cut in self.cuts]

    # ------------------------------------------------------------------ #
    # Aggregations
    # ------------------------------------------------------------------ #
    def plane_locators(self, axis: str | None = None) -> np.ndarray:
        """Return one scalar coordinate per plane along ``axis``.

        For axis-aligned sweeps (horizontal grid, vertical grid), all
        planes share a normal aligned with a global axis; the locator
        is that coordinate of each plane's point — z for horizontal
        cuts, x or y for vertical cuts.

        When ``axis`` is ``None`` and the first plane normal is nearly
        aligned with a global axis (tolerance 1e-6 on each component),
        the axis is inferred from that normal. Pass ``axis="x"`` etc.
        explicitly for oblique sweeps where inference doesn't apply.
        """
        if not self.cuts:
            return np.zeros((0,))
        if axis is None:
            n0 = np.asarray(self.cuts[0].plane_normal, dtype=float)
            if abs(abs(n0[2]) - 1.0) < 1e-6:
                axis = "z"
            elif abs(abs(n0[0]) - 1.0) < 1e-6:
                axis = "x"
            elif abs(abs(n0[1]) - 1.0) < 1e-6:
                axis = "y"
            else:
                raise ValueError(
                    "Cannot infer axis from oblique plane normal "
                    f"{n0.tolist()}; pass axis='x'|'y'|'z' explicitly."
                )
        key = axis.strip().lower()
        if key not in ("x", "y", "z"):
            raise ValueError(f"axis must be 'x', 'y', or 'z'; got {axis!r}.")
        col = {"x": 0, "y": 1, "z": 2}[key]
        return np.array(
            [cut.plane_point[col] for cut in self.cuts], dtype=float,
        )

    # ------------------------------------------------------------------ #
    # Container protocol
    # ------------------------------------------------------------------ #
    def __len__(self) -> int:
        return len(self.cuts)

    def __getitem__(self, i: int) -> SectionCutDef:
        return self.cuts[i]

    def __iter__(self) -> Iterator[SectionCutDef]:
        return iter(self.cuts)

    def __repr__(self) -> str:
        return f"SectionSweepDef(n_planes={len(self.cuts)})"

    @property
    def n_planes(self) -> int:
        return len(self.cuts)

    @property
    def is_empty(self) -> bool:
        return not self.cuts

    # ------------------------------------------------------------------ #
    # Pickle — matches SectionCutDef
    # ------------------------------------------------------------------ #
    def save_pickle(
        self,
        path: str | Path,
        *,
        compress: bool | None = None,
        protocol: int = pickle.HIGHEST_PROTOCOL,
    ) -> Path:
        p = Path(path)
        if compress is None:
            compress = p.suffix.lower() == ".gz"
        opener = gzip.open if compress else open
        with opener(p, "wb") as f:
            pickle.dump(self, f, protocol=protocol)
        return p

    @classmethod
    def load_pickle(cls, path: str | Path) -> "SectionSweepDef":
        p = Path(path)
        opener = gzip.open if p.suffix.lower() == ".gz" else open
        with opener(p, "rb") as f:
            obj = pickle.load(f)
        if not isinstance(obj, cls):
            raise TypeError(
                f"Pickled object is {type(obj).__name__}, expected {cls.__name__}."
            )
        return obj
